sudo: false

language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  # TODO(rhcarvalho): check syntax of other important entrypoint playbooks
  - ansible-playbook --syntax-check playbooks/byo/config.yml
  - cd utils && make ci
  - make test-integration
