---
- hosts: OSEv3
  vars:
    openshift_deployment_type: "{{ deployment_type | default('openshift-enterprise') }}"
  roles:
    - openshift_version

- hosts: OSEv3
  name: determine if yum update will work
  tasks:
  - action: check_yum_update
    when:
      - containerized is undefined or not containerized

- hosts: masters
  name: determine if yum install of master pkgs will work
  tasks:
  - name: main packages for enterprise
    when:
      - containerized is undefined or not containerized
      - deployment_type == "openshift-enterprise"
      - openshift_release == "3.3"
    check_yum_update:
      packages:
        - atomic-openshift
        - atomic-openshift-clients
        - atomic-openshift-master
  - name: main packages for origin
    when:
      - containerized is undefined or not containerized
      - deployment_type == "origin"
    check_yum_update:
      packages:
        - origin
        - origin-clients
        - origin-master
  - name: other master packages
    when:
      - containerized is undefined or not containerized
    check_yum_update:
      packages:
        - etcd
        - bash-completion
        - cockpit-bridge
        - cockpit-docker
        - cockpit-kubernetes
        - cockpit-shell
        - cockpit-ws
        - httpd-tools

- hosts: nodes
  name: determine if yum install of node pkgs will work
  tasks:
  - name: main packages for enterprise
    when:
      - containerized is undefined or not containerized
      - deployment_type == "openshift-enterprise"
      - openshift_release == "3.3"
    check_yum_update:
      packages:
        - atomic-openshift
        - atomic-openshift-node
        - atomic-openshift-sdn-ovs
  - name: main packages for origin
    when:
      - containerized is undefined or not containerized
      - deployment_type == "origin"
    check_yum_update:
      packages:
        - origin
        - origin-node
        - origin-sdn-ovs
  - name: other node packages
    when:
      - containerized is undefined or not containerized
    check_yum_update:
      packages:
        - docker
        - PyYAML
        - firewalld
        - iptables
        - iptables-services
        - nfs-utils
        - ntp
        - yum-utils
        - dnsmasq
        - libselinux-python
        - ceph-common
        - glusterfs-fuse
        - iscsi-initiator-utils
        - pyparted
        - python-httplib2
        - openssl
        - flannel
        - bind
