---
- name: Verify Ansible version is greater than or equal to 2.2.0
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
  - name: Verify Ansible version is greater than or equal to 2.2.0
    fail:
      msg: "Unsupported ansible version: {{ ansible_version.full }} found"
    when: not ansible_version.full | version_compare('2.2.0', 'ge')
